- hosts: harvester
  remote_user: '{{ remote_user }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Copy check script to remote server
      copy:
        src: '{{ chia_path }}/chia-ops/scripts/check-hdd.sh'
        dest: '{{ chia_path }}'
        owner: '{{ remote_user }}'
        group: '{{ remote_user }}'
        mode: +x

    - name: Chia version
      shell: '{{ chia_path }}/check-hdd.sh'
      register: check_result

    - name: Echo check result
      debug:
        msg: '{{ check_result.stdout }}'