- hosts: harvester
  remote_user: '{{ remote_user }}'
  gather_facts: no
  tasks:
    - name: Install plotman and generate plotman config
      shell: |
        source /home/chia/chia/chia-blockchain/activate
        pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main
        plotman config generate
      args:
        executable: /bin/bash