- hosts: harvest
  remote_user: '{{ remote_user }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create chia path
      file:
        path: '{{ chia_path }}'
        state: directory
        owner: '{{ remote_user }}'
        group: '{{ remote_user }}'
        mode: u=rwxr,g=xr,o=x

    - name: Copy mount hdd to remote server
      copy:
        src: '{{ chia_path }}/chia-ops/scripts/mount-hdd.sh'
        dest: '{{ chia_path }}'
        owner: '{{ remote_user }}'
        group: '{{ remote_user }}'
        mode: +x

    - name: Mount hdd
      shell: '{{ chia_path }}/mount-hdd.sh'
