- hosts: harvester
  remote_user: '{{ remote_user }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Source chia
      shell: echo 'source /home/chia/chia/chia-blockchain/activate' >> /home/chia/.profile